In [4]:
import numpy as np


In [8]:
list_ =["1","2","3","4","5"]
array_list = np.array(object = list_)

In [9]:
# Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
# to print the data types of both the variables.


In [10]:
list_

['1', '2', '3', '4', '5']

In [11]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [12]:
# Q2. Write a code to print the data type of each and every element of both the variables list_ and
# arra_list.


In [13]:
type(list_)

list

In [14]:
type(array_list)

numpy.ndarray

In [15]:
# Q3. Considering the following changes in the variable, array_list:
# array_list = np.array(object = list_, dtype = int)
# Will there be any difference in the data type of the elements present in both the variables, list_ and
# arra_list? If so then print the data types of each and every element present in both the variables, list_
# and arra_list.

In [16]:
array_list = np.array(object = list_, dtype = int)

In [19]:
array_list

array([1, 2, 3, 4, 5])

In [20]:
type(array_list)

numpy.ndarray

In [22]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [23]:
type(num_list)

list

In [24]:
type(num_array)

numpy.ndarray

In [18]:
list_

['1', '2', '3', '4', '5']

In [21]:
type(list_)

list

In [26]:
# Q4. Write a code to find the following characteristics of variable, num_array:
# (i) shape
# (ii) size


In [28]:
num_array.shape

(2, 3)

In [29]:
num_array.size

6

In [30]:
# Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
# creation function.
# [Hint: The size of the array will be 9 and the shape will be (3,3).]

In [33]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [34]:
# Create an identity matrix of shape (5,5) using numpy functions?


In [36]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])